### ISSUE TITLE
standard deviation calculation is wrong

### ISSUE THREAD

**Issue by helinwang** [ae6rt/golang-examples#1]
```
func stdDev(numbers []float64, mean float64) float64 {
    total := 0.0
    for _, number := range numbers {
        total += math.Pow(number-mean, 2)
    }
    variance := total / float64(len(numbers)-1)
    return math.Sqrt(variance)
}
```

should be `variance := total / float64(len(numbers))` rather than `variance := total / float64(len(numbers)-1)`

**Comment by kaos** [comment]
This could perhaps have to do with Bessel's correction.. ?

> Dividing by n−1 gives a better estimate of the population standard deviation for the larger parent population than dividing by n, which gives a result which is correct for the sample only. This is known as Bessel's correction.[5]

  https://en.wikipedia.org/wiki/Standard_deviation

What I miss here would be an extra argument specifying if we're dealing with the entire population, or just a statistical sample of it.
